FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY helloworld-blazorserver.csproj .
RUN dotnet restore "helloworld-blazorserver.csproj"
COPY . .
RUN dotnet build "helloworld-blazorserver.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "helloworld-blazorserver.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "helloworld-blazorserver.dll"]