FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY helloworld-blazorwasm.csproj .
RUN dotnet restore "helloworld-blazorwasm.csproj"
COPY . .
RUN dotnet build "helloworld-blazorwasm.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "helloworld-blazorwasm.csproj" -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/helloworld-blazorwasm/dist .
COPY nginx.conf /etc/nginx/nginx.conf
